os:
  - windows

language: c

env:
  - BRANCH=1.2.4

cache:
  directories:
    - "$HOME/.choosenim"

if: tag IS blank

install:
  - set -e
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh
  - curl "https://bintray.com/genotrance/binaries/download_file?file_path=boehmgc64-stripped.dll" -LsSf -o boehmgc64.dll
  - export BUILD_DATE=$(date +'%Y%m%d%H%M')
  - export GIT_HASH=$(git log --format=%h -1)
  - export GIT_HASH_FULL=$(git rev-parse HEAD)
  - export TRAVIS_TAG="${BUILD_DATE}-${GIT_HASH}"

script:
  - set -e
  - nimble develop -y
  - nimble binary
  - 7z a feud-${TRAVIS_TAG}.zip *.exe feud.ini plugins/*.dll plugins/server/*.dll plugins/client/*.dll boehmgc64.dll

before_deploy:
  - git config --local user.name "${GIT_TAG_USER_NAME}"
  - git config --local user.email "${GIT_TAG_USER_EMAIL}"
  - git tag "${TRAVIS_TAG}" || echo "${TRAVIS_TAG} already exists"

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "feud-${TRAVIS_TAG}.zip"
  name: "${TRAVIS_TAG}"
  body: >-
    This release was built on $(date +'%Y-%m-%d') using https://github.com/genotrance/feud/tree/${GIT_HASH_FULL}.

  skip_cleanup: true
  on:
    branch: master
